import type { Product } from "@/types";

// ═══════════════════════════════════════════
// SAMPLE PRODUCTS — 10 products for launch
// Using generated product images in /products/
// ═══════════════════════════════════════════

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Carbon Fiber Ultra Case",
    slug: "carbon-fiber-ultra-case-iphone-16-pro-max",
    description: "Ultra-thin real carbon fiber case with military-grade protection. Weighs just 12g. MagSafe compatible with N52 magnets.",
    price: 1499,
    mrp: 2999,
    phoneBrand: "Apple",
    phoneModel: "iPhone 16 Pro Max",
    caseType: "Carbon Fiber",
    material: "carbon_fiber",
    color: "Black",
    colorHex: "#1A1A1A",
    stockQty: 45,
    sku: "LW-001",
    images: ["/products/carbon-fiber.png"],
    videoUrl: null,
    badge: "BESTSELLER",
    status: "published",
    featured: true,
    showInTrending: true,
    showInDeviceSelector: true,
    costPrice: 350,
    weight: 12,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    reviews: [
      { id: "r1", productId: "1", customerName: "Arjun S.", orderId: "LW-0001", rating: 5, comment: "Best case ever! Super lightweight yet strong.", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
      { id: "r2", productId: "1", customerName: "Priya M.", orderId: "LW-0012", rating: 5, comment: "Looks amazing. MagSafe works perfectly.", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
      { id: "r3", productId: "1", customerName: "Rahul K.", orderId: "LW-0023", rating: 4, comment: "Great quality, fast delivery.", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
    ],
  },
  {
    id: "2",
    name: "Aramid Shield Pro",
    slug: "aramid-shield-pro-iphone-16-pro",
    description: "Premium aramid fiber case with 5x strength of steel. Invisible MagSafe ring. Anti-scratch coating.",
    price: 1899,
    mrp: 3499,
    phoneBrand: "Apple",
    phoneModel: "iPhone 16 Pro",
    caseType: "Aramid Fiber",
    material: "aramid",
    color: "Matte Black",
    colorHex: "#0D0D0D",
    stockQty: 32,
    sku: "LW-002",
    images: ["/products/aramid-fiber.png"],
    videoUrl: null,
    badge: "NEW",
    status: "published",
    featured: true,
    showInTrending: true,
    showInDeviceSelector: true,
    costPrice: 450,
    weight: 15,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    reviews: [
      { id: "r4", productId: "2", customerName: "Vikram J.", orderId: "LW-0034", rating: 5, comment: "Premium feel! Worth every rupee.", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
      { id: "r5", productId: "2", customerName: "Sneha D.", orderId: "LW-0045", rating: 5, comment: "Super slim. Can't even feel it.", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
    ],
  },
  {
    id: "3",
    name: "MagSafe Crystal Clear",
    slug: "magsafe-crystal-clear-iphone-16",
    description: "Anti-yellow clear case with MagSafe ring. Lifetime clarity guarantee. Drop tested from 10ft.",
    price: 899,
    mrp: 1999,
    phoneBrand: "Apple",
    phoneModel: "iPhone 16",
    caseType: "MagSafe",
    material: "polycarbonate",
    color: "Crystal Clear",
    colorHex: "#E8E8E8",
    stockQty: 78,
    sku: "LW-003",
    images: ["/products/magsafe-clear.png"],
    videoUrl: null,
    badge: "BESTSELLER",
    status: "published",
    featured: true,
    showInTrending: true,
    showInDeviceSelector: true,
    costPrice: 150,
    weight: 20,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    reviews: [
      { id: "r6", productId: "3", customerName: "Amit T.", orderId: "LW-0056", rating: 5, comment: "Finally a clear case that doesn't yellow!", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
      { id: "r7", productId: "3", customerName: "Neha G.", orderId: "LW-0067", rating: 4, comment: "Love the MagSafe alignment. Great.", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
      { id: "r8", productId: "3", customerName: "Karan P.", orderId: "LW-0078", rating: 5, comment: "Best value MagSafe case!", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
      { id: "r9", productId: "3", customerName: "Simran L.", orderId: "LW-0089", rating: 5, comment: "My phone looks so sleek.", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
    ],
  },
  {
    id: "4",
    name: "Rose Blossom Cute Case",
    slug: "rose-blossom-cute-case-iphone-16-pro-max",
    description: "Adorable floral design with reinforced bumper. Soft-touch silicone. Perfect for her! 💖",
    price: 699,
    mrp: 1499,
    phoneBrand: "Apple",
    phoneModel: "iPhone 16 Pro Max",
    caseType: "Cute",
    material: "silicone",
    color: "Rose Pink",
    colorHex: "#FF6B9D",
    stockQty: 55,
    sku: "LW-004",
    images: ["/products/cute-pink.png"],
    videoUrl: null,
    badge: "FOR_HER",
    status: "published",
    featured: true,
    showInTrending: true,
    showInDeviceSelector: true,
    costPrice: 120,
    weight: 25,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    reviews: [
      { id: "r10", productId: "4", customerName: "Ananya S.", orderId: "LW-0100", rating: 5, comment: "So cute! My friends love it! 💖", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
      { id: "r11", productId: "4", customerName: "Diya R.", orderId: "LW-0111", rating: 5, comment: "Beautiful design, great grip.", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
    ],
  },
  {
    id: "5",
    name: "Carbon Fiber Ultra Case",
    slug: "carbon-fiber-ultra-case-samsung-s26-ultra",
    description: "Ultra-thin real carbon fiber case designed for Samsung Galaxy S26 Ultra. MIL-STD-810G drop tested.",
    price: 1499,
    mrp: 2999,
    phoneBrand: "Samsung",
    phoneModel: "Galaxy S26 Ultra",
    caseType: "Carbon Fiber",
    material: "carbon_fiber",
    color: "Black",
    colorHex: "#1A1A1A",
    stockQty: 28,
    sku: "LW-005",
    images: ["/products/carbon-fiber.png"],
    videoUrl: null,
    badge: "NEW",
    status: "published",
    featured: true,
    showInTrending: true,
    showInDeviceSelector: true,
    costPrice: 350,
    weight: 14,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    reviews: [
      { id: "r12", productId: "5", customerName: "Rohan V.", orderId: "LW-0122", rating: 5, comment: "Perfect fit for my S26 Ultra!", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
    ],
  },
  {
    id: "6",
    name: "Aramid Shield Pro",
    slug: "aramid-shield-pro-samsung-s25-ultra",
    description: "Premium aramid fiber protection for Samsung Galaxy S25 Ultra. Featherweight yet bulletproof.",
    price: 1899,
    mrp: 3499,
    phoneBrand: "Samsung",
    phoneModel: "Galaxy S25 Ultra",
    caseType: "Aramid Fiber",
    material: "aramid",
    color: "Gunmetal",
    colorHex: "#2C3E50",
    stockQty: 19,
    sku: "LW-006",
    images: ["/products/aramid-fiber.png"],
    videoUrl: null,
    badge: null,
    status: "published",
    featured: false,
    showInTrending: true,
    showInDeviceSelector: true,
    costPrice: 450,
    weight: 16,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    reviews: [
      { id: "r13", productId: "6", customerName: "Manish A.", orderId: "LW-0133", rating: 4, comment: "Solid protection, slim profile.", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
      { id: "r14", productId: "6", customerName: "Pooja F.", orderId: "LW-0144", rating: 5, comment: "Best aramid case available!", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
    ],
  },
  {
    id: "7",
    name: "Butterfly Dreams Case",
    slug: "butterfly-dreams-cute-case-iphone-15-pro",
    description: "Enchanting butterfly pattern with glitter accents. Shockproof silicone. A dream in your hand! ✨",
    price: 599,
    mrp: 1299,
    phoneBrand: "Apple",
    phoneModel: "iPhone 15 Pro",
    caseType: "Cute",
    material: "silicone",
    color: "Lavender",
    colorHex: "#B983FF",
    stockQty: 62,
    sku: "LW-007",
    images: ["/products/cute-lavender.png"],
    videoUrl: null,
    badge: "FOR_HER",
    status: "published",
    featured: false,
    showInTrending: true,
    showInDeviceSelector: true,
    costPrice: 100,
    weight: 28,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    reviews: [
      { id: "r15", productId: "7", customerName: "Ishita M.", orderId: "LW-0155", rating: 5, comment: "Obsessed with the butterfly design! 🦋", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
    ],
  },
  {
    id: "8",
    name: "Leather Luxe MagSafe",
    slug: "leather-luxe-magsafe-iphone-16-pro-max",
    description: "Premium vegan leather with magnetic MagSafe ring. Soft-touch finish. Ages beautifully.",
    price: 1299,
    mrp: 2499,
    phoneBrand: "Apple",
    phoneModel: "iPhone 16 Pro Max",
    caseType: "MagSafe",
    material: "leather",
    color: "Saddle Brown",
    colorHex: "#8B4513",
    stockQty: 3,
    sku: "LW-008",
    images: ["/products/leather-brown.png"],
    videoUrl: null,
    badge: "LOW_STOCK",
    status: "published",
    featured: true,
    showInTrending: true,
    showInDeviceSelector: true,
    costPrice: 280,
    weight: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    reviews: [
      { id: "r16", productId: "8", customerName: "Deepak S.", orderId: "LW-0166", rating: 5, comment: "Luxury feel! MagSafe is perfect.", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
      { id: "r17", productId: "8", customerName: "Kavita N.", orderId: "LW-0177", rating: 4, comment: "Beautiful leather, great quality.", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
      { id: "r18", productId: "8", customerName: "Suresh G.", orderId: "LW-0188", rating: 5, comment: "Worth the price for sure!", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
    ],
  },
  {
    id: "9",
    name: "Carbon Fiber Slim",
    slug: "carbon-fiber-slim-iphone-15-pro-max",
    description: "The thinnest carbon fiber case ever made. Just 0.6mm. Zero bulk, maximum protection.",
    price: 1199,
    mrp: 2299,
    phoneBrand: "Apple",
    phoneModel: "iPhone 15 Pro Max",
    caseType: "Carbon Fiber",
    material: "carbon_fiber",
    color: "Black",
    colorHex: "#111111",
    stockQty: 40,
    sku: "LW-009",
    images: ["/products/carbon-fiber.png"],
    videoUrl: null,
    badge: null,
    status: "published",
    featured: false,
    showInTrending: true,
    showInDeviceSelector: true,
    costPrice: 300,
    weight: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    reviews: [
      { id: "r19", productId: "9", customerName: "Vivek R.", orderId: "LW-0199", rating: 5, comment: "Incredibly thin! Can't even feel it.", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
      { id: "r20", productId: "9", customerName: "Nisha B.", orderId: "LW-0200", rating: 4, comment: "Great case, fast shipping.", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
    ],
  },
  {
    id: "10",
    name: "Cherry Blossom Case",
    slug: "cherry-blossom-cute-case-samsung-s26-ultra",
    description: "Beautiful sakura design with TPU bumper protection. Designed for the Samsung Galaxy S26 Ultra.",
    price: 699,
    mrp: 1499,
    phoneBrand: "Samsung",
    phoneModel: "Galaxy S26 Ultra",
    caseType: "Cute",
    material: "silicone",
    color: "Sakura Pink",
    colorHex: "#FFB7C5",
    stockQty: 48,
    sku: "LW-010",
    images: ["/products/cute-pink.png"],
    videoUrl: null,
    badge: "FOR_HER",
    status: "published",
    featured: false,
    showInTrending: true,
    showInDeviceSelector: true,
    costPrice: 110,
    weight: 26,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    reviews: [
      { id: "r21", productId: "10", customerName: "Meera K.", orderId: "LW-0211", rating: 5, comment: "Perfect for my Samsung! Love the design.", images: [], verified: true, approved: true, createdAt: new Date().toISOString() },
    ],
  },
];
